entry:
  argon: ./src/argon.js
  boron: ./src/boron.js
  carbon: ./src/carbon.js
output: out # It is not necessary to specify a file name when multiple files are output. Automatically convert to [name].js
js:
  flow: true
  react: true
css:
  modules: true
  postcss: true
html:
  filename: index.html
  template: ./index.ejs
dev:
  env: .env.dev
  port: 8080
  dashboard: true
prod:
  env: .env.prod
  url: true
  extract: true
